"""
Schema-drift guard for the user_memories lifecycle columns.

The repo already has a migration whose entire purpose was closing drift
between hand-written DDL and its SQLModel class (f6a7b8c9d0e1, which added
seven id indexes so ``alembic revision --autogenerate`` came back empty).
That drift is silent — nothing fails until a later autogenerated migration
tries to re-create an index that already exists — so it is worth an
executable check rather than a review-time convention.

This asserts the migration, the models and the lifecycle policy module all
tell the same story. It imports the migration module rather than grepping its
source, because the DDL is assembled from module-level tuples at runtime.
"""
import importlib.util
import pathlib

import backend.app.infrastructure.database.engine  # noqa: F401  (populates metadata)
import pytest
from backend.app.services.memory_lifecycle import CONFIDENCE_FLOOR, INITIAL_CONFIDENCE
from sqlmodel import SQLModel

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
_MIGRATION_PATH = (
    _REPO_ROOT / "backend/migrations/versions/b1c2d3e4f5a6_user_memory_lifecycle.py"
)
_NEW_COLUMNS = ("mem0_id", "retrieval_count", "last_used_at", "scope")
_NEW_INDEXED = ("mem0_id", "scope")


@pytest.fixture(scope="module")
def migration():
    spec = importlib.util.spec_from_file_location("mig_b1c2d3e4f5a6", _MIGRATION_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def model_columns() -> set[str]:
    return {c.name for c in SQLModel.metadata.tables["user_memories"].columns}


def test_migration_file_exists():
    assert _MIGRATION_PATH.exists(), f"missing migration: {_MIGRATION_PATH}"


def test_every_added_column_is_declared_on_the_model(migration, model_columns):
    added = {name for name, _ddl in migration._NEW_COLUMNS}
    assert added == set(_NEW_COLUMNS)
    missing = added - model_columns
    assert not missing, f"migration adds columns the model does not declare: {missing}"


def test_indexed_columns_have_their_columns_created_first(migration):
    indexed = {col for _name, _table, col in migration._NEW_INDEXES}
    added = {name for name, _ddl in migration._NEW_COLUMNS}
    assert indexed == set(_NEW_INDEXED)
    assert indexed <= added, "cannot index a column the migration never creates"


def test_index_names_match_the_model_avoiding_autogenerate_drift(migration):
    """A mismatched name is exactly the drift f6a7b8c9d0e1 was written to fix."""
    model_index_names = {
        idx.name for tbl in SQLModel.metadata.tables.values() for idx in tbl.indexes
    }
    for name, _table, _col in migration._NEW_INDEXES:
        assert name in model_index_names, (
            f"index '{name}' matches no model index; autogenerate would report drift"
        )
    # The converse: a model index on a new column with no migration counterpart.
    for col in _NEW_INDEXED:
        assert f"ix_user_memories_{col}" in {n for n, _t, _c in migration._NEW_INDEXES}


def test_downgrade_reverses_exactly_what_upgrade_adds(migration):
    src = _MIGRATION_PATH.read_text(encoding="utf-8")
    assert "reversed(_NEW_COLUMNS)" in src
    assert "reversed(_NEW_INDEXES)" in src


def test_every_statement_is_idempotent(migration):
    """Guarded DDL, so a database built by create_all also upgrades cleanly."""
    src = _MIGRATION_PATH.read_text(encoding="utf-8")
    assert "ADD COLUMN IF NOT EXISTS" in src
    assert "CREATE INDEX IF NOT EXISTS" in src
    assert "DROP INDEX IF EXISTS" in src
    assert "DROP COLUMN IF EXISTS" in src


def test_migration_and_policy_agree_on_initial_confidence(migration):
    assert float(migration._INITIAL_CONFIDENCE) == INITIAL_CONFIDENCE


def test_model_default_is_no_longer_degenerate_always_certain():
    """The bug: confidence defaulted to 1.0 and was never lowered."""
    default = SQLModel.metadata.tables["user_memories"].columns["confidence"].default
    value = getattr(default, "arg", default)
    assert 0.0 < float(value) < 1.0, f"confidence default is degenerate: {value}"


def test_floor_sits_below_the_initial_confidence():
    """Otherwise every memory is born already decayed."""
    assert CONFIDENCE_FLOOR < INITIAL_CONFIDENCE
