"""align plan/artifact/bandit/hook/optimization/redteam tables with their models

Revision ID: f6a7b8c9d0e1
Revises: e5f6a7b8c9d0
Create Date: 2026-09-28 12:00:00.000000

Closes the schema drift left by the three feature migrations
(a1b2c3d4e5f6, c1d2e3f4a5b6) so ``alembic revision --autogenerate`` is empty.

Those migrations created their tables with hand-written DDL that did not quite
match the SQLModel classes: each model declares ``index=True`` on its primary
key, so ``create_all`` would have produced an ``ix_<table>_id`` index, but the
hand-written ``CREATE TABLE`` did not. Alembic compares metadata against the
live database, so the difference surfaced as seven CREATE INDEX operations that
would reappear in every future autogenerated migration.

Adding the indexes here — rather than leaving them to autogenerate — keeps the
change reviewable and idempotent. It is purely additive: no data is read,
rewritten, or dropped, and the tables are all empty of production rows.

Safety notes:
  * Every op is guarded with IF NOT EXISTS, matching the convention used by the
    other migrations in this directory, so a database where the indexes already
    exist (because ``create_all`` built the table instead) also succeeds.
  * Index-only change, so the operation is fast and does not lock the tables
    for a rewrite.
"""
from typing import Sequence, Union

from alembic import op

revision: str = "f6a7b8c9d0e1"
down_revision: Union[str, None] = "e5f6a7b8c9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (index name, table) for every model whose primary key declares index=True.
_MISSING_ID_INDEXES = (
    ("ix_plans_id", "plans"),
    ("ix_hook_policies_id", "hook_policies"),
    ("ix_artifacts_id", "artifacts"),
    ("ix_artifact_versions_id", "artifact_versions"),
    ("ix_bandit_rewards_id", "bandit_rewards"),
    ("ix_prompt_optimization_runs_id", "prompt_optimization_runs"),
    ("ix_redteam_runs_id", "redteam_runs"),
)


def upgrade() -> None:
    for index_name, table in _MISSING_ID_INDEXES:
        op.execute(f"CREATE INDEX IF NOT EXISTS {index_name} ON {table} (id)")


def downgrade() -> None:
    for index_name, _table in reversed(_MISSING_ID_INDEXES):
        op.execute(f"DROP INDEX IF EXISTS {index_name}")
